// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxOzLYdrywnJFAy--XT-PGaYNDQNuqq7Y',
    appId: '1:280534192610:web:656355ccef07ef0353a9bb',
    messagingSenderId: '280534192610',
    projectId: 'furniture-app-72aa2',
    authDomain: 'furniture-app-72aa2.firebaseapp.com',
    storageBucket: 'furniture-app-72aa2.firebasestorage.app',
    measurementId: 'G-XSGPHQVLNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4zYxaUlDA5k2NNPoEF8UzlMuJ7L-9aWI',
    appId: '1:280534192610:android:44a06dbec29a1be353a9bb',
    messagingSenderId: '280534192610',
    projectId: 'furniture-app-72aa2',
    storageBucket: 'furniture-app-72aa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkDEQUA4CSyKEyyEDmGaeBlq_Sbu_4b20',
    appId: '1:280534192610:ios:65f140d62cf1547d53a9bb',
    messagingSenderId: '280534192610',
    projectId: 'furniture-app-72aa2',
    storageBucket: 'furniture-app-72aa2.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkDEQUA4CSyKEyyEDmGaeBlq_Sbu_4b20',
    appId: '1:280534192610:ios:65f140d62cf1547d53a9bb',
    messagingSenderId: '280534192610',
    projectId: 'furniture-app-72aa2',
    storageBucket: 'furniture-app-72aa2.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxOzLYdrywnJFAy--XT-PGaYNDQNuqq7Y',
    appId: '1:280534192610:web:28e61d7cf46fbec853a9bb',
    messagingSenderId: '280534192610',
    projectId: 'furniture-app-72aa2',
    authDomain: 'furniture-app-72aa2.firebaseapp.com',
    storageBucket: 'furniture-app-72aa2.firebasestorage.app',
    measurementId: 'G-X0TGNPKKPS',
  );

}