// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnsaN9NdeJ2dw4uFox6SZ8sLCOlKvwWHY',
    appId: '1:41511272716:web:6c1eb6e1c2ad7d3e078929',
    messagingSenderId: '41511272716',
    projectId: 'example-84431',
    authDomain: 'example-84431.firebaseapp.com',
    storageBucket: 'example-84431.firebasestorage.app',
    measurementId: 'G-SBH56LMKEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSnoxUHTXRDT-KTmbTHQ2fpzJ1FQbmxaY',
    appId: '1:41511272716:android:4837b0d50622ef33078929',
    messagingSenderId: '41511272716',
    projectId: 'example-84431',
    storageBucket: 'example-84431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcLIh00Aop9_myfj1oH3ej1c6Wzj61kIs',
    appId: '1:41511272716:ios:2f611aaa602c9c70078929',
    messagingSenderId: '41511272716',
    projectId: 'example-84431',
    storageBucket: 'example-84431.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcLIh00Aop9_myfj1oH3ej1c6Wzj61kIs',
    appId: '1:41511272716:ios:2f611aaa602c9c70078929',
    messagingSenderId: '41511272716',
    projectId: 'example-84431',
    storageBucket: 'example-84431.firebasestorage.app',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnsaN9NdeJ2dw4uFox6SZ8sLCOlKvwWHY',
    appId: '1:41511272716:web:9fa7e2a540743b44078929',
    messagingSenderId: '41511272716',
    projectId: 'example-84431',
    authDomain: 'example-84431.firebaseapp.com',
    storageBucket: 'example-84431.firebasestorage.app',
    measurementId: 'G-XLNH4YWMCS',
  );
}
